"""empty message

Revision ID: 381a84d91b90
Revises: 
Create Date: 2019-04-27 19:57:24.235737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381a84d91b90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
